config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActivityPub::Engine => 'ap'

  authenticate :user do
    mount ExceptionHunter::Engine => 'exception_hunter'
    mount GoodJob::Engine => 'good_job'
    mount ActivityPubUi::Engine => 'ap_ui'
    mount ActivityPub::ObjectAttachmentUploader.upload_endpoint(:cache) => '/panel/object_attachments/upload'
  end

  get "up" => "rails/health#show", as: :rails_health_check

  get '.well-known/webfinger', to: 'activity_pub/well_known/webfinger#show', as: :webfinger
  get '.well-known/host-meta', to: 'activity_pub/well_known/host_meta#show', as: :host_meta
  get '.well-known/nodeinfo', to: 'activity_pub/well_known/node_info#show', as: :node_info
  get '.well-known/nodeinfo/2.0', to: 'activity_pub/well_known/node_info#v20', as: :node_info_v20

  resources :conversations, only: [:index, :show]
  resources :topics, only: [] do
    resources :conversations, only: [:index]
  end

  namespace :panel do
    resources :objects, only: [:index, :new, :show, :create, :edit, :update] do
      get 'new/article', action: :new_article, on: :collection, as: :new_article
      get :replies_preview
      post :like, on: :member
      post :unlike, on: :member
    end

    resources :comments, only: [:show] do
      post :like, on: :member
      post :unlike, on: :member
    end

    resources :actors, only: [] do
      post :follow, on: :member
      post :unfollow, on: :member

      resources :objects, only: [:index, :show]
    end

    resources :uploads, only: [:create]
    resource :design, controller: :design, only: [:edit, :update]
    resource :settings, only: [:edit, :update]

    root to: 'objects#index'
  end

  get 'uploads/:signed_id/redirect', to: 'uploads#redirect', as: :upload_redirect

  resources :objects, path: :posts, controller: 'public/objects', only: [:index, :show]

  root to: 'public/objects#index'
end

app/controllers/panel/actors_controller.rb
module Panel
  class ActorsController < PanelController
    def follow
      Accounts::Follower.run(actor: current_site.activity_pub_object, target: find_account)

      render turbo_stream: turbo_stream.replace(
        helpers.dom_id(find_account, :follow_btn),
        Actors::FollowBtnComponent.new(actor: current_site.activity_pub_object, target_actor: find_account)
      )
    end

    def unfollow
      Accounts::Unfollower.run(actor: current_site.activity_pub_object, target: find_account)

      render turbo_stream: turbo_stream.replace(
        helpers.dom_id(find_account, :follow_btn),
        Actors::FollowBtnComponent.new(actor: current_site.activity_pub_object, target_actor: find_account)
      )
    end

    private

    def find_account
      @find_account ||= ActivityPub::Object.find(params[:id])
    end
  end
end

app/controllers/panel/comments_controller.rb
module Panel
  class CommentsController < PanelController
    before_action :authenticate_user!

    def like
      @ap_object = ActivityPub::Note.find(params[:id])
      @like = Objects::Liker.run(actor: current_site.activity_pub_object, target: @ap_object).like

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_back fallback_location: panel_comment_path(@ap_object) }
      end
    end

    def unlike
      @ap_object = ActivityPub::Note.find(params[:id])
      Objects::Unliker.run(actor: current_site.activity_pub_object, target: @ap_object)
      @ap_object.reload

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_back fallback_location: panel_comment_path(@ap_object) }
      end
    end

    private

    def find_actor
      @find_actor ||= ActivityPub::Object.find(params[:actor_id])
    end
  end
end

app/controllers/panel/design_controller.rb
module Panel
  class DesignController < PanelController
    def edit
      @object = current_site
    end

    def update
      @object = current_site

      if @object.update(design_params)
        redirect_to edit_panel_design_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def design_params
      params.require(:design).permit(:template_markup)
    end
  end
end

app/controllers/panel/objects_controller.rb
module Panel
  class ObjectsController < PanelController
    before_action :authenticate_user!

    OBJECT_TYPES = [
      ActivityPub::Note,
      ActivityPub::Article,
    ]

    def index
      @objects = ActivityPub::Object.where(type: OBJECT_TYPES.map(&:name))
                                    .not_replies

      if params[:actor_id]
        @actor = find_actor
        @objects = @objects.joins(:attributed_to)
                           .where(attributed_tos_activity_pub_objects: { id: @actor.id })
      else
        @objects = @objects.left_joins(:attributed_to)
                           .where(attributed_tos_activity_pub_objects: { id: current_site.activity_pub_object.following.map(&:id).push(current_site.activity_pub_object.id).uniq })
        @objects = @objects
      end

      @objects = @objects.order('created_at DESC, activity_pub_objects.id')
                         .limit(25)
      @liked_object_ids = current_site.activity_pub_object
                                      .likes
                                      .joins(:target_ap_object)
                                      .where(target_ap_object: { id: @objects.map(&:id) })
                                      .pluck(:target_ap_object_id)
    end

    def show
      @object = ActivityPub::Object.find(params[:id])
      @comments = ActivityPub::Object.descendants_of(@object)
                                     .includes(:attributed_to)
      @liked_comment_ids = current_site.activity_pub_object
                                       .likes.joins(:target_ap_object)
                                       .where(target_ap_object: { id: @comments.map(&:id) })
                                       .pluck(:target_ap_object_id)
      @liked_object_ids = current_site.activity_pub_object
                                      .likes
                                      .joins(:target_ap_object)
                                      .where(target_ap_object: { id: @object.id })
                                      .pluck(:target_ap_object_id)
    end

    def replies_preview
      @object = ActivityPub::Object.find(params[:object_id])
      render Objects::RepliesPreviewComponent.new(@object, loaded: true)
    end

    def new
      redirect_to new_article_panel_objects_path
    end

    def new_article
      @ap_object = current_site.activity_pub_object.attributions.new.becomes(ActivityPub::Article)
    end

    def create
      @ap_object = current_site.activity_pub_object.attributions.create!(
        ap_object_params.merge(
          type: ActivityPub::Article.name,
          published_at: Time.current
        )
      )

      redirect_to panel_object_path(@ap_object)
    end

    def edit
      @ap_object = current_site.activity_pub_object.attributions.find(params[:id])
    end

    def update
      @ap_object = current_site.activity_pub_object.attributions.find(params[:id])

      if @ap_object.update(ap_object_params)
        redirect_to panel_object_path(@ap_object)
      else
        render :edit
      end
    end

    def like
      @ap_object = ActivityPub::Object.find(params[:id])
      @like = Objects::Liker.run(actor: current_site.activity_pub_object, target: @ap_object).like

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_back fallback_location: panel_objects_path }
      end
    end

    def unlike
      @ap_object = ActivityPub::Object.find(params[:id])
      Objects::Unliker.run(actor: current_site.activity_pub_object, target: @ap_object)

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_back fallback_location: panel_objects_path }
      end
    end

    private

    def find_actor
      @find_actor ||= ActivityPub::Object.find(params[:actor_id])
    end

    def ap_object_params
      params.require(:ap_object).permit(:content_raw, :name)
    end
  end
end

app/controllers/panel/searches_controller.rb
module Panel
  class SearchesController < PanelController
    def create
      @form = Groups::SearchForm.run!(current_ap_actor: current_group, query: params[:query])

      redirect_to panel_object_path(@form)
    end
  end
end

app/controllers/panel/settings_controller.rb
module Panel
  class SettingsController < PanelController
    def edit
      @object = current_site
    end

    def update
      @object = current_site

      if @object.update(settings_params)
        redirect_to edit_panel_settings_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def settings_params
      params.require(:settings).permit(:avatar, activity_pub_object_attributes: [:name, :summary])
    end
  end
end

app/controllers/panel/uploads_controller.rb
module Panel
  class UploadsController < PanelController
    def create
      upload = Upload.create(upload_params)

      if upload.valid?
        render json: {
          success: 1,
          file: {
            id: upload.file.id,
            url: upload_redirect_path(upload.signed_id),
            width: upload.file.width,
            height: upload.file.height
          }
        }, status: :created
      else
        render json: { success: 0, errors: upload.errors.full_messages },
               status: :unprocessable_entity
      end
    end

    private

    def upload_params
      params.require(:upload).permit(:file)
    end
  end
end

app/controllers/panel_controller.rb
class PanelController < ApplicationController
  before_action :authenticate_user!

  layout 'panel'

  private

  def current_actor
    current_user.activity_pub_object
  end
end

app/views/panel/objects/_attachment_form.html.erb
<div class="media-uploader-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <div class="h-32 max-w-full rounded-sm bg-gray-500 bg-cover" style="background-image: url('PREVIEW_URL')"></div>
  <%= f.hidden_field :file, value: 'SIGNED_ID', class: 'hidden' %>
</div>

app/views/panel/objects/_comment.html.erb
<% author = comment.attributed_to[0] %>
<% author_decorated = AuthorDecorator.new(author) %>

<li>
  <div class="flex flex-row mt-0 pb-3 pt-2 mx-0">
    <div class="w-auto h-auto rounded-full">
      <%= link_to panel_actor_objects_path(actor_id: author&.id) do %>
        <%= image_tag author_decorated.avatar_url, size: '36x36', class: 'w-9 h-9 object-cover rounded-full cursor-pointer' %>
      <% end %>
    </div>

    <div class="flex flex-col ml-3 flex-1">
      <div class="text-gray-600 text-sm font-semibold">
        <%= link_to author.name, panel_actor_objects_path(actor_id: author&.id) %>
      </div>
      <div class="flex w-full mt-0">
        <div class="text-gray-700 text-xs mr-1 cursor-pointer">
          <%= link_to author_decorated.display_username, panel_actor_objects_path(actor_id: author&.id) %>
        </div>
        <div class="text-gray-400 text-xs">
          <%= link_to panel_object_url(comment) do %>
            • <%= time_ago_in_words(comment.created_at) %> ago
          <% end %>
        </div>

        <% if comment.remote? %>
          <div class="text-gray-400 text-xs ml-1">
            • <%= link_to 'url', comment.guid %>
          </div>
        <% end %>

        <% if comment.local? %>
          <div class="text-gray-400 text-xs ml-1">
            • <%= link_to 'edit', edit_panel_object_path(comment) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="text-gray-700 [&_p]:mb-3">
    <%== comment.content %>
  </div>

  <%= render 'panel/comments/footer', comment: comment, liked_comment_ids: liked_comment_ids %>

  <ul class="ml-2 pl-6 mt-4 pt-0 border-l">
    <% replies.each do |comment, children| %>
      <%= render('panel/objects/comment', comment: comment, replies: children, liked_comment_ids: liked_comment_ids) %>
    <% end %>
  </ul>
</li>

app/views/panel/objects/edit.html.erb
<%= render(Ui::TwoColumnsLayoutComponent.new) do |layout| %>
  <%= layout.with_right do %>
    <div class="text-gray-700">
      <%= form_with model: @ap_object, url: panel_object_path(@ap_object), scope: :ap_object, data: { controller: 'media-uploader-form', nested_form_wrapper_selector_value: '.media-uploader-form-wrapper', action: 'media-uploader:uploaded->media-uploader-form#add' } do |f| %>
        <%= render(Ui::TopBarComponent.new) do |top_bar| %>
          <% top_bar.with_left do %>
            <%= f.text_field :name, class: 'text-xl' %>
          <% end %>

          <% top_bar.with_actions do %>
            <%= render(Ui::BtnComponent.new(type: :submit)) do %>
              Save
            <% end %>
          <% end %>
        <% end %>

        <div
          data-controller="editorjs"
          class="content"
        >
          <div data-editorjs-target="editor"></div>
          <%= f.hidden_field :content_raw, data: { editorjs_target: :input } %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/panel/objects/index.html.erb
<%= render(Ui::TwoColumnsLayoutComponent.new) do |layout| %>
  <% layout.with_right do %>
    <% if @actor %>
      <% actor_decorated = AuthorDecorator.new(@actor) %>

      <div class="grid grid-cols-12 mt-6 mb-16 max-w-3xl mx-auto items-center">
        <div class="col-span-3 flex">
          <%= image_tag actor_decorated.avatar_url, class: 'w-32 h-32 object-cover rounded-full justify-self' %>
        </div>

        <div class="col-span-9">
          <div class="flex gap-4 items-center">
            <h1 class="text-xl">
              <%= @actor.name %>
            </h1>

            <span class="text-sm text-gray-500 pt-1">
              <%= actor_decorated.display_username %>
            </span>

            <%= render(Actors::FollowBtnComponent.new(
              actor: current_site.activity_pub_object,
              target_actor: @actor
            )) %>
          </div>

          <div class="text-sm mt-4 text-gray-700">
            <%= simple_format @actor.summary %>
          </div>

          <div class="flex gap-6 mt-4 text-sm">
            <span><%= pluralize(@actor.attributions_count, 'post') %></span>
            <span><%= pluralize(@actor.followers_count, 'followers') %></span>
            <span><%= @actor.following_count %> following</span>
          </div>
        </div>
      </div>
    <% end %>

    <% if @objects.any? %>
      <% @objects.each do |obj| %>
        <%= render(Objects::WrapComponent.new(obj, current_ap_actor: current_site.activity_pub_object, liked_ap_object_ids: @liked_object_ids)) %>
      <% end %>
    <% else %>
      no objects
    <% end %>
  <% end %>
<% end %>

app/views/panel/objects/like.turbo_stream.erb
<turbo-stream action="replace" target="<%= dom_id(@ap_object, :footer) %>">
  <template>
    <%= render(Objects::FooterComponent.new(@ap_object, current_ap_actor: current_site.activity_pub_object,
                                                        liked_ap_object_ids: [@like.target_ap_object_id])) %>
  </template>
</turbo-stream>

app/views/panel/objects/new.html.erb
<%= render(Ui::TwoColumnsLayoutComponent.new) do |layout| %>
  <% layout.with_left do %>
    <%= render(Groups::SidebarComponent.new(current_group)) %>
  <% end %>

  <%= layout.with_right do %>
    <div class="text-gray-700">
      <h1 class="text-xl mb-2">Add post</h1>
      <hr class="mb-5">

      <%= form_with model: @ap_object, url: panel_objects_path, data: { controller: 'media-uploader-form', nested_form_wrapper_selector_value: '.media-uploader-form-wrapper', action: 'media-uploader:uploaded->media-uploader-form#add' } do |f| %>
        <template data-media-uploader-form-target="template">
          <%= f.fields_for :ap_attachments, @ap_object.ap_attachments.new, child_index: 'NEW_RECORD' do |attachment_fields| %>
            <%= render "attachment_form", f: attachment_fields %>
          <% end %>
        </template>

        <div class="grid grid-cols-2 gap-8">
          <div>
            <h2 class="mb-3">Media</h2>
            <p class="text-gray-500 mb-4 text-sm">You can include up to 10 files. If you need more, consider switching to <a href="#">post editor</a> instead.</p>

            <div class="cursor-pointer mb-4 bg-gray-100 p-10 border-dashed border-gray-200 border-2 text-center rounded-sm" data-controller="media-uploader" data-action="click->media-uploader#selectFiles" data-media-uploader-direct-upload-url-value="<%= rails_direct_uploads_path %>">
              <input type="file" data-media-uploader-target="input" class="hidden" data-action="media-uploader#upload" multiple>

              <svg xmlns="http://www.w3.org/2000/svg" class="mx-auto w-10 h-10 text-gray-400 mb-2" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M7 18a4.6 4.4 0 0 1 0 -9a5 4.5 0 0 1 11 2h1a3.5 3.5 0 0 1 0 7h-1" />
                <path d="M9 15l3 -3l3 3" />
                <path d="M12 12l0 9" />
              </svg>

              <p class="font-medium">Drop your file(s) here, or <a href="#">Browse</a> to upload</p>
              <p class="text-gray-400 text-sm">Maximum file size of 10MB</p>
            </div>

            <div class="grid grid-cols-2 md:grid-cols-3 gap-4 mb-5">
              <div data-media-uploader-form-target="target" class="hidden"></div>
            </div>
          </div>

          <div>
            <h2 class="mb-2">Description</h2>
            <p class="text-gray-500 mb-4 text-sm">Include some text description with your post. Might be a post title, might be a backstory - whatever needed.</p>
            <textarea rows="7" class="text optional w-full py-1 px-2 rounded-md border border-gray-200 transition focus:outline-none focus:ring-2 focus:ring-gray-600 focus:border-transparent"></textarea>
          </div>
        </div>

        <%= f.submit %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/panel/objects/new_article.html.erb
<%= render(Ui::TwoColumnsLayoutComponent.new) do |layout| %>
  <%= layout.with_right do %>
    <%= form_with model: @ap_object, url: panel_objects_path, scope: :ap_object, data: { controller: 'media-uploader-form', nested_form_wrapper_selector_value: '.media-uploader-form-wrapper', action: 'media-uploader:uploaded->media-uploader-form#add' } do |f| %>
      <%= render(Ui::TopBarComponent.new) do |top_bar| %>
        <% top_bar.with_left do %>
          <%= f.text_field :name, value: (f.object.name || 'Untitled'), class: 'text-xl' %>
        <% end %>

        <% top_bar.with_actions do %>
          <%= render(Ui::BtnComponent.new(type: :submit)) do %>
            Save
          <% end %>
        <% end %>
      <% end %>

      <div
        data-controller="editorjs"
        class="content"
      >
        <div data-editorjs-target="editor"></div>
        <%= f.hidden_field :content_raw, data: { editorjs_target: :input } %>
      </div
    <% end %>
  <% end %>
<% end %>

app/views/panel/objects/show.html.erb
<%= render(Ui::TwoColumnsLayoutComponent.new) do |layout| %>
  <% layout.with_right do %>
    <div class="max-w-3xl mx-auto">
      <%= render(Objects::WrapComponent.new(@object, current_ap_actor: current_site.activity_pub_object, liked_ap_object_ids: @liked_object_ids, replies: @replies, show_replies: false)) %>

      <h5 class="font-bold mb-3">Replies</h5>
      <ul>
        <% @comments.arrange(order: :created_at).each do |comment, replies| %>
          <%= render('panel/objects/comment', comment: comment, replies: replies, liked_comment_ids: @liked_comment_ids) %>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/panel/objects/unlike.turbo_stream.erb
<turbo-stream action="replace" target="<%= dom_id(@ap_object, :footer) %>">
  <template>
    <%= render(Objects::FooterComponent.new(@ap_object, current_ap_actor: current_site.activity_pub_object, liked_ap_object_ids: [])) %>
  </template>
</turbo-stream>