config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActivityPub::Engine => 'ap'

  authenticate :user do
    mount ExceptionHunter::Engine => 'exception_hunter'
    mount GoodJob::Engine => 'good_job'
    mount ActivityPubUi::Engine => 'ap_ui'
    mount ActivityPub::ObjectAttachmentUploader.upload_endpoint(:cache) => '/panel/object_attachments/upload'
  end

  get "up" => "rails/health#show", as: :rails_health_check

  get '.well-known/webfinger', to: 'activity_pub/well_known/webfinger#show', as: :webfinger
  get '.well-known/host-meta', to: 'activity_pub/well_known/host_meta#show', as: :host_meta
  get '.well-known/nodeinfo', to: 'activity_pub/well_known/node_info#show', as: :node_info
  get '.well-known/nodeinfo/2.0', to: 'activity_pub/well_known/node_info#v20', as: :node_info_v20

  resources :conversations, only: [:index, :show]
  resources :topics, only: [] do
    resources :conversations, only: [:index]
  end

  namespace :panel do
    resources :objects, only: [:index, :new, :show, :create, :edit, :update] do
      get 'new/article', action: :new_article, on: :collection, as: :new_article
      get :replies_preview
      post :like, on: :member
      post :unlike, on: :member
    end

    resources :comments, only: [:show] do
      post :like, on: :member
      post :unlike, on: :member
    end

    resources :actors, only: [] do
      post :follow, on: :member
      post :unfollow, on: :member

      resources :objects, only: [:index, :show]
    end

    resources :uploads, only: [:create]
    resource :design, controller: :design, only: [:edit, :update]
    resource :settings, only: [:edit, :update]

    root to: 'objects#index'
  end

  get 'uploads/:signed_id/redirect', to: 'uploads#redirect', as: :upload_redirect

  resources :objects, path: :posts, controller: 'public/objects', only: [:index, :show]

  root to: 'public/objects#index'
end

app/controllers/panel/actors_controller.rb
module Panel
  class ActorsController < PanelController
    def follow
      Accounts::Follower.run(actor: current_site.activity_pub_object, target: find_account)

      render turbo_stream: turbo_stream.replace(
        helpers.dom_id(find_account, :follow_btn),
        Actors::FollowBtnComponent.new(actor: current_site.activity_pub_object, target_actor: find_account)
      )
    end

    def unfollow
      Accounts::Unfollower.run(actor: current_site.activity_pub_object, target: find_account)

      render turbo_stream: turbo_stream.replace(
        helpers.dom_id(find_account, :follow_btn),
        Actors::FollowBtnComponent.new(actor: current_site.activity_pub_object, target_actor: find_account)
      )
    end

    private

    def find_account
      @find_account ||= ActivityPub::Object.find(params[:id])
    end
  end
end

app/controllers/panel/comments_controller.rb
module Panel
  class CommentsController < PanelController
    before_action :authenticate_user!

    def like
      @ap_object = ActivityPub::Note.find(params[:id])
      @like = Objects::Liker.run(actor: current_site.activity_pub_object, target: @ap_object).like

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_back fallback_location: panel_comment_path(@ap_object) }
      end
    end

    def unlike
      @ap_object = ActivityPub::Note.find(params[:id])
      Objects::Unliker.run(actor: current_site.activity_pub_object, target: @ap_object)
      @ap_object.reload

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_back fallback_location: panel_comment_path(@ap_object) }
      end
    end

    private

    def find_actor
      @find_actor ||= ActivityPub::Object.find(params[:actor_id])
    end
  end
end

app/controllers/panel/design_controller.rb
module Panel
  class DesignController < PanelController
    def edit
      @object = current_site
    end

    def update
      @object = current_site

      if @object.update(design_params)
        redirect_to edit_panel_design_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def design_params
      params.require(:design).permit(:template_markup)
    end
  end
end

app/controllers/panel/objects_controller.rb
module Panel
  class ObjectsController < PanelController
    before_action :authenticate_user!

    OBJECT_TYPES = [
      ActivityPub::Note,
      ActivityPub::Article,
    ]

    def index
      @objects = ActivityPub::Object.where(type: OBJECT_TYPES.map(&:name))
                                    .not_replies

      if params[:actor_id]
        @actor = find_actor
        @objects = @objects.joins(:attributed_to)
                           .where(attributed_tos_activity_pub_objects: { id: @actor.id })
      else
        @objects = @objects.left_joins(:attributed_to)
                           .where(attributed_tos_activity_pub_objects: { id: current_site.activity_pub_object.following.map(&:id).push(current_site.activity_pub_object.id).uniq })
        @objects = @objects
      end

      @objects = @objects.order('created_at DESC, activity_pub_objects.id')
                         .limit(25)
      @liked_object_ids = current_site.activity_pub_object
                                      .likes
                                      .joins(:target_ap_object)
                                      .where(target_ap_object: { id: @objects.map(&:id) })
                                      .pluck(:target_ap_object_id)
    end

    def show
      @object = ActivityPub::Object.find(params[:id])
      @comments = ActivityPub::Object.descendants_of(@object)
                                     .includes(:attributed_to)
      @liked_comment_ids = current_site.activity_pub_object
                                       .likes.joins(:target_ap_object)
                                       .where(target_ap_object: { id: @comments.map(&:id) })
                                       .pluck(:target_ap_object_id)
      @liked_object_ids = current_site.activity_pub_object
                                      .likes
                                      .joins(:target_ap_object)
                                      .where(target_ap_object: { id: @object.id })
                                      .pluck(:target_ap_object_id)
    end

    def replies_preview
      @object = ActivityPub::Object.find(params[:object_id])
      render Objects::RepliesPreviewComponent.new(@object, loaded: true)
    end

    def new
      redirect_to new_article_panel_objects_path
    end

    def new_article
      @ap_object = current_site.activity_pub_object.attributions.new.becomes(ActivityPub::Article)
    end

    def create
      @ap_object = current_site.activity_pub_object.attributions.create!(
        ap_object_params.merge(
          type: ActivityPub::Article.name,
          published_at: Time.current
        )
      )

      redirect_to panel_object_path(@ap_object)
    end

    def edit
      @ap_object = current_site.activity_pub_object.attributions.find(params[:id])
    end

    def update
      @ap_object = current_site.activity_pub_object.attributions.find(params[:id])

      if @ap_object.update(ap_object_params)
        redirect_to panel_object_path(@ap_object)
      else
        render :edit
      end
    end

    def like
      @ap_object = ActivityPub::Object.find(params[:id])
      @like = Objects::Liker.run(actor: current_site.activity_pub_object, target: @ap_object).like

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_back fallback_location: panel_objects_path }
      end
    end

    def unlike
      @ap_object = ActivityPub::Object.find(params[:id])
      Objects::Unliker.run(actor: current_site.activity_pub_object, target: @ap_object)

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_back fallback_location: panel_objects_path }
      end
    end

    private

    def find_actor
      @find_actor ||= ActivityPub::Object.find(params[:actor_id])
    end

    def ap_object_params
      params.require(:ap_object).permit(:content_raw, :name)
    end
  end
end

app/controllers/panel/searches_controller.rb
module Panel
  class SearchesController < PanelController
    def create
      @form = Groups::SearchForm.run!(current_ap_actor: current_group, query: params[:query])

      redirect_to panel_object_path(@form)
    end
  end
end

app/controllers/panel/settings_controller.rb
module Panel
  class SettingsController < PanelController
    def edit
      @object = current_site
    end

    def update
      @object = current_site

      if @object.update(settings_params)
        redirect_to edit_panel_settings_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def settings_params
      params.require(:settings).permit(:avatar, activity_pub_object_attributes: [:name, :summary])
    end
  end
end

app/controllers/panel/uploads_controller.rb
module Panel
  class UploadsController < PanelController
    def create
      upload = Upload.create(upload_params)

      if upload.valid?
        render json: {
          success: 1,
          file: {
            id: upload.file.id,
            url: upload_redirect_path(upload.signed_id),
            width: upload.file.width,
            height: upload.file.height
          }
        }, status: :created
      else
        render json: { success: 0, errors: upload.errors.full_messages },
               status: :unprocessable_entity
      end
    end

    private

    def upload_params
      params.require(:upload).permit(:file)
    end
  end
end

app/controllers/panel_controller.rb
class PanelController < ApplicationController
  before_action :authenticate_user!

  layout 'panel'

  private

  def current_actor
    current_user.activity_pub_object
  end
end

app/views/panel/settings/edit.html.erb
<%= render(Ui::TwoColumnsLayoutComponent.new) do |layout| %>
  <% layout.with_right do %>
    <%= form_with model: @object, url: panel_settings_path, scope: :settings, method: :patch do |f| %>
      <%= render(Ui::TopBarComponent.new) do |top_bar| %>
        <% top_bar.with_title do %>
          Site settings
        <% end %>

        <% top_bar.with_actions do %>
          <%= render(Ui::BtnComponent.new(type: :submit)) do %>
            Save
          <% end %>
        <% end %>
      <% end %>

      <div class="grid grid-cols-12 gap-6">
        <div class="col-span-4">
          <h4 class="font-bold mb-2">Name and meta</h4>
          <p class="text-sm text-gray-400">
            Name and meta information about your website determines how it's presented on other instances
          </p>
        </div>

        <div class="col-span-8">
          <%= render(Ui::CardComponent.new) do |card| %>
            <% card.with_body do %>
              <label for="" class="block font-semibold mb-2 text-sm">Website name</label>
              <div class="mb-4">
                <%= f.fields_for :activity_pub_object do |ff| %>
                  <%= ff.text_field :name, class: 'w-full py-1 px-2 rounded-md border border-gray-200 transition focus:outline-none focus:ring-2 focus:ring-gray-600 focus:border-transparent' %>
                <% end %>
              </div>

              <label for="" class="block font-semibold mb-2 text-sm">Description</label>
              <%= f.fields_for :activity_pub_object do |ff| %>
                <%= ff.text_area :summary, rows: 5, class: 'w-full py-1 px-2 rounded-md border border-gray-200 transition focus:outline-none focus:ring-2 focus:ring-gray-600 focus:border-transparent' %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <hr class="mb-4">

      <div class="grid grid-cols-12 gap-6">
        <div class="col-span-4">
          <h4 class="font-bold mb-2">Images</h4>
          <p class="text-sm text-gray-400">
            Setup an avatar that will represent your website across entire fediverse
          </p>
        </div>

        <div class="col-span-8">
          <%= render(Ui::CardComponent.new) do |card| %>
            <% card.with_body do %>
              <label for="" class="block font-semibold mb-2 text-sm">Avatar</label>
              <div class="flex mb-4">
                <% if current_site.avatar %>
                  <div class="flex-1">
                    <%= image_tag f.object.avatar_url, class: 'rounded-full', size: 100 %>
                  </div>
                <% end %>
                <div class="pl-5">
                  <%= f.file_field :avatar %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>