activity_pub_ui/config/routes.rb
ActivityPubUi::Engine.routes.draw do
  resources :objects, only: [:index, :show] do
    post :resolve, on: :collection
  end

  resources :inbound_request_logs, only: [:index, :show]
  resources :outbound_request_logs, only: [:index, :show]
end

activity_pub_ui/app/models/activity_pub_ui/application_record.rb
module ActivityPubUi
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

activity_pub_ui/app/controllers/activity_pub_ui/application_controller.rb
module ActivityPubUi
  class ApplicationController < ActionController::Base
  end
end

activity_pub_ui/app/controllers/activity_pub_ui/inbound_request_logs_controller.rb
module ActivityPubUi
  class InboundRequestLogsController < ApplicationController
    include Pagy::Backend

    def index
      @q = InboundRequestLog.all.ransack(params[:q])
      @q.sorts = 'started_at desc' if @q.sorts.empty?
      @pagy, @requests = pagy(@q.result)
    end

    def show
      @request = InboundRequestLog.find(params[:id])
    end
  end
end

activity_pub_ui/app/controllers/activity_pub_ui/objects_controller.rb
module ActivityPubUi
  class ObjectsController < ApplicationController
    include Pagy::Backend

    def index
      @q = ActivityPub::Object.all.ransack(params[:q])
      @q.sorts = 'created_at desc' if @q.sorts.empty?
      @pagy, @objects = pagy(@q.result)
    end

    def show
      @object = ActivityPub::Object.find(params[:id])
      @in_reply_to = ActivityPub::Object.where(guid: [@object.data['inReplyTo']])
      @replies = ActivityPub::Object.where(guid: [@object.data['attributedTo']])
    end

    def resolve
      @object = ActivityPub::RootObjectResolver.new(params[:uri]).call
      redirect_to object_path(@object)
    end
  end
end

activity_pub_ui/app/controllers/activity_pub_ui/outbound_request_logs_controller.rb
module ActivityPubUi
  class OutboundRequestLogsController < ApplicationController
    include Pagy::Backend

    def index
      @q = OutboundRequestLog.all.ransack(params[:q])
      @q.sorts = 'started_at desc' if @q.sorts.empty?
      @pagy, @requests = pagy(@q.result)
    end

    def show
      @request = OutboundRequestLog.find(params[:id])
    end
  end
end

activity_pub_ui/app/helpers/activity_pub_ui/application_helper.rb
module ActivityPubUi
  module ApplicationHelper
    include Pagy::Frontend
  end
end

activity_pub_ui/app/views/activity_pub_ui/follows/_row.html.erb
<tr class="justify-content-center">
  <td>
    <%= link_to object.id, object_path(object), class: 'text-decoration-none font-monospace' %>
    <div class="text-muted small"><%= object.guid %></div>
  </td>
  <td><code><%= object.type %></code></td>
  <td>Object status: <%= object.status %></td>
  <td>Follow state: <%= follow.state %></td>
  <td><%= object.created_at %></td>
  <td><%= object.last_synced_at %></td>
</tr>

activity_pub_ui/app/views/activity_pub_ui/objects/_row.html.erb
<tr class="justify-content-center">
  <td>
    <%= link_to object.id, object_path(object), class: 'text-decoration-none font-monospace' %>
    <div class="text-muted small"><%= object.guid %></div>
  </td>
  <td><code><%= object.type %></code></td>
  <td><%= object.status %></td>
  <td><%= object.created_at %></td>
  <td><%= object.last_synced_at %></td>
</tr>

activity_pub_ui/app/views/activity_pub_ui/objects/index.html.erb
<table class="table align-middle">
  <thead>
    <th>ID</th>
    <th><%= sort_link(@q, :type) %></th>
    <th><%= sort_link(@q, :status) %></th>
    <th><%= sort_link(@q, :created_at) %></th>
    <th><%= sort_link(@q, :last_synced_at) %></th>
  </thead>
  <tbody>
    <%= render collection: @objects, partial: 'row', as: :object %>
  </tbody>
</table>

<%== pagy_bootstrap_nav(@pagy) %>

activity_pub_ui/app/views/activity_pub_ui/objects/show.html.erb
<div class="row mb-5">
  <div class="col-12">
    <h1 class="mb-1"><%= @object.id %></h1>
    <h5 class="text-secondary"><%= @object.guid %></h5>
  </div>
</div>

<div class="row">
  <div class="col-7">
    <% if @object.error_message %>
      <h3>Error message</h3>
      <code><%= @object.error_message %></code>
    <% end %>

    <h3>Data</h3>
    <pre><%= JSON.pretty_generate @object.data %></pre>
  </div>

  <div class="col-5">
    <h3>In reply to</h3>
    <% if @object.in_reply_to %>
      <%= link_to @object.in_reply_to.guid, object_path(@object.in_reply_to) %></li>
    <% end %>

    <h3 class="mt-4">Attributed to</h3>
    <ul>
      <% @object.attributed_to.each do |object| %>
        <li><%= link_to object.guid, object_path(object) %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <h3 class="mt-4">Attributions</h3>
    <table class="table align-middle">
      <tbody>
        <% @object.attributions.each do |object| %>
          <%= render 'row', object: object %>
        <% end %>
      </tbody>
    </table>

    <h3 class="mt-4">Announced</h3>
    <ul>
      <% @object.announced.limit(5).each do |announce| %>
        <li><%= link_to announce.guid, ap_object_path(announce) %></li>
      <% end %>
    </ul>

    <h3 class="mt-4">Replies</h3>
    <table class="table align-middle">
      <tbody>
        <% @object.replies.each do |object| %>
          <%= render 'row', object: object %>
        <% end %>
      </tbody>
    </table>

    <h3 class="mt-4">Followers</h3>
    <table class="table align-middle">
      <tbody>
        <% @object.followers_associations.each do |follow| %>
          <%= render 'activity_pub_ui/follows/row', follow: follow, object: follow.source_ap_object %>
        <% end %>
      </tbody>
    </table>

    <h3 class="mt-4">Following</h3>
    <table class="table align-middle">
      <tbody>
        <% @object.following_associations.each do |follow| %>
          <%= render 'activity_pub_ui/follows/row', follow: follow, object: follow.target_ap_object %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

activity_pub_ui/app/views/activity_pub_ui/outbound_request_logs/index.html.erb
<table class="table">
  <thead>
    <th><%= sort_link(@q, :id) %></th>
    <th><%= sort_link(@q, :method) %></th>
    <th><%= sort_link(@q, :code) %></th>
    <th>Path</th>
    <th><%= sort_link(@q, :started_at) %></th>
    <th><%= sort_link(@q, :ended_at) %></th>
    <th>Loggable</th>
  </thead>

  <% @requests.each do |request| %>
    <tr>
      <td><%= link_to request.id, request %></td>
      <td><%= request.method %></td>
      <td><%= request.response_code %></td>
      <td><code><%= request.path %></code></td>
      <td><%= request.started_at %></td>
      <td><%= request.ended_at %></td>
      <td><%= [request.loggable_type, request.loggable_id].join(':') %></td>
    </tr>
  <% end %>
</table>

<%== pagy_bootstrap_nav(@pagy) %>

activity_pub_ui/app/views/activity_pub_ui/outbound_request_logs/show.html.erb
<h1><code><%= @request.path %></code></h1>
<h4 class="mb-4 text-secondary"><%= @request.method %> <%= @request.response_code %> • <%= @request.started_at %> → <%= @request.ended_at %></h4>

<h3>Related object</h3>
<div class="mb-3">
  <% if @request.loggable&.is_a?(ActivityPub::Object) %>
    <%= link_to @request.loggable.becomes(ActivityPub::Object) do %>
      <code><%= [@request.loggable_type, @request.loggable_id].join(':') %></code>
    <% end %>
  <% end %>
</div>

<h3>Request body</h3>
<pre><%= JSON.pretty_generate @request.request_body %></pre>

<h3>Request headers</h3>
<pre><%= JSON.pretty_generate(JSON.parse(@request.request_headers)) %></pre>

<h3>Response body</h3>
<pre><%= @request.response_body %></pre>

activity_pub_ui/app/views/layouts/activity_pub_ui/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Activity pub ui</title>

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary mb-4">
      <div class="container">
        <a class="navbar-brand" href="<%= objects_path %>">ActivityPub</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="<%= objects_path %>">Objects</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= inbound_request_logs_path %>">Inbound Requests</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= outbound_request_logs_path %>">Outbound Requests</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= main_app.good_job_path %>">Jobs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= main_app.exception_hunter_path %>">Exceptions</a>
            </li>
          </ul>
          <%= form_with url: resolve_objects_path, class: 'd-flex', method: :post do %>
            <input class="form-control me-2" type="search" placeholder="Object URI" name="uri">
            <button class="btn btn-outline-success" type="submit">Resolve</button>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>